repos:
  - repo: https://github.com/mondeja/project-config
    rev: fix
    hooks:
      - id: project-config
  - repo: meta
    hooks:
      - id: check-hooks-apply
        name: check-hooks-apply
      - id: check-useless-excludes
        name: check-useless-excludes
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --remove-duplicate-keys
          - --ignore-init-module-imports
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
      - id: add-trailing-comma
        name: add-trailing-comma
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
      - id: end-of-file-fixer
        name: end-of-file-fixer
      - id: debug-statements
        name: debug-statements
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort-src
        alias: isort-src
        files: ^src
        args:
          - --add-import
          - from __future__ import annotations
      - id: isort
        name: isort-meta
        alias: isort-meta
        files: ^(docs|tests)
  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 2.0.0
    hooks:
      - id: flakeheaven
        additional_dependencies:
          - flake8-builtins
          - flake8-comprehensions
          - flake8-docstrings
          - flake8-executable
          - flake8-implicit-str-concat
          - flake8-print
          - flake8-printf-formatting
          - flake8-pytest-style
          - pysetenv
        entry: pysetenv FLAKEHEAVEN_CACHE_TIMEOUT=0 flakeheaven lint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or:
          - toml
          - css
          - json
          - json5
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
        minimum_pre_commit_version: 2.9.0
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        files: ^src
        additional_dependencies:
          - types-PyYAML
          - types-tabulate
          - types-jmespath
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.2.0
    hooks:
      - id: remove-crlf
        files: \.bat$
        name: '*.bat end of lines'
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
      - id: editorconfig-checker
        name: editorconfig-checker
        alias: ec
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args:
          - -c
          - .yamllint.yaml
