repos:
  - repo: https://github.com/mondeja/project-config
    rev: v0.8.0
    hooks:
      - id: project-config
  - repo: meta
    hooks:
      - id: check-hooks-apply
        name: check-hooks-apply
      - id: check-useless-excludes
        name: check-useless-excludes
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.7.0
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
  - repo: https://github.com/myint/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --remove-duplicate-keys
          - --ignore-init-module-imports
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.5.1
    hooks:
      - id: add-trailing-comma
        name: add-trailing-comma
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
      - id: end-of-file-fixer
        name: end-of-file-fixer
      - id: debug-statements
        name: debug-statements
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort-src
        alias: isort-src
        files: ^src
        args:
          - --add-import
          - from __future__ import annotations
      - id: isort
        name: isort-meta
        alias: isort-meta
        files: ^(docs|tests)
  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.3.0
    hooks:
      - id: flakeheaven
        additional_dependencies:
          - flake8-builtins
          - flake8-comprehensions
          - flake8-docstrings
          - flake8-executable
          - flake8-implicit-str-concat
          - flake8-print
          - flake8-printf-formatting
          - flake8-pytest-style
          - flake8-bugbear
          - flake8-encodings
          - flake8-no-pep420
          - flake8-absolute-import
          - flake8-slots
          - flake8-unused-arguments
          - dlint
          - pysetenv
        entry: pysetenv FLAKEHEAVEN_CACHE_TIMEOUT=0 flakeheaven lint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        types_or:
          - toml
          - css
          - json
          - json5
          - yaml
          - markdown
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
        minimum_pre_commit_version: 2.9.0
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.8.1
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        files: ^src
        additional_dependencies:
          - types-pyyaml
          - types-tabulate
          - types-jmespath
          - types-appdirs
          - pytest
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: remove-crlf
        files: \.bat$
        name: "*.bat end of lines"
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.2
    hooks:
      - id: editorconfig-checker
        name: editorconfig-checker
        alias: ec
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args:
          - -c
          - .yamllint.yaml
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.11.2
    hooks:
      - id: markdown-link-check
        name: markdown-link-check
