repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
        name: check-hooks-apply
      - id: check-useless-excludes
        name: check-useless-excludes
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.1
    hooks:
      - id: add-trailing-comma
        name: add-trailing-comma
        args:
          - --py37-plus
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --remove-duplicate-keys
          - --ignore-init-module-imports
  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 1.0.1
    hooks:
      - id: flakeheaven
        additional_dependencies:
          - flake8-builtins
          - flake8-comprehensions
          - flake8-docstrings
          - flake8-executable
          - flake8-implicit-str-concat
          - flake8-print
          - flake8-printf-formatting
          - flake8-pytest-style
          - pysetenv
        entry: pysetenv FLAKEHEAVEN_CACHE_TIMEOUT=0 flakeheaven lint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
      - id: end-of-file-fixer
        name: end-of-file-fixer
      - id: debug-statements
        name: debug-statements
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        types_or:
          - toml
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.960
    hooks:
      - id: mypy
        files: ^src
        additional_dependencies:
          - types-PyYAML
          - types-tabulate
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
      - id: editorconfig-checker
        name: editorconfig-checker
        alias: ec
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args:
          - -c
          - .yamllint.yaml
