[tool.poetry]
name = "project-config"
version = "0.1.0"
description = "Reproducible configuration across projects."
authors = ["Álvaro Mondéjar Rubio <mondejar1994@gmail.com>"]
license = "BSD-3-License"
readme = "README.md"
packages = [{ include = "project_config", from = "src" }]

[tool.poetry.dependencies]
python = "^3.7"
tomlkit = "^0.11.0"
importlib-metadata-argparse-version = "^0.1.0"

[tool.poetry.scripts]
project-config = "project_config.__main__:main"

[tool.mypy]
python_version = "3.7"
strict = true
