descriptor_id: PROJECT_CONFIG
descriptor_type: tooling_format
descriptor_flavors:
  - all_flavors
file_extensions:
  - "*"
active_only_if_file_found:
  - .project-config.toml
  - pyproject.toml
linters:
  - linter_name: project-config
    linter_url: https://mondeja.github.io/project-config/
    name: PROJECT_CONFIG
    install:
      dockerfile:
        - RUN pip install project-config
    examples:
      - project-config check
      - project-config fix
    lint_all_files: true
    cli_lint_mode: project
    cli_lint_errors_count: regex_count
    cli_lint_errors_regex: "  - .+"
    cli_help_arg_name: --help
    cli_lint_extra_args:
      - check
    cli_lint_fix_arg_name: fix
    cli_lint_fix_remove_args:
      - check
    linter_spdx_license: BSD-3-Clause
    linter_megalinter_ref_url: https://mondeja.github.io/project-config/latest/install.html
    linter_repo: https://github.com/mondeja/project-config
    linter_rules_configuration_url: https://mondeja.github.io/project-config/latest/reference/styling.html
    linter_rules_url: https://mondeja.github.io/project-config/latest/reference/plugins.html
    linter_version_cache: 0.9.1
